In [21]:
#Import packages
import pandas as pd
import numpy as np
import re

In [22]:
#Membaca CSV hasil crawling menjadi DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/RandyTunru/PersonalDatasets/master/Tugas%20Akhir/Jakarta%20(6).csv")

In [23]:
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,1772458999792668889,Tue Mar 26 03:02:10 +0000 2024,274,Waktu dpt rejection letter di satu uni di UK. ...,1772458999792668889,https://pbs.twimg.com/ext_tw_video_thumb/17724...,NaN,in,NaN,7,2,15,https://twitter.com/busanonni/status/177245899...,934597254324789249,busanonni
1,1774471350603952134,Sun Mar 31 16:18:32 +0000 2024,1552,230923 SMTOWN in JAKARTA #태용 #AprilFoolsDay #만...,1774471350603952134,https://pbs.twimg.com/media/GKAwRnAa8AA6pvw.jpg,NaN,in,"_shotaroo_ / LOGO CROP, 2차가공 X",20,0,693,https://twitter.com/NovBreeze1125/status/17744...,1589994125897891842,NovBreeze1125
2,1773245752170459149,Thu Mar 28 07:08:27 +0000 2024,5821,Ini harga TDS2 7Drean()scape di Jakarta setela...,1773245752170459149,https://pbs.twimg.com/media/GJvVm2BakAEtWKM.jpg,NaN,in,loving jeno,1378,161,2242,https://twitter.com/jenonoom/status/1773245752...,1741406757908561920,jenonoom
3,1772836901873127452,Wed Mar 27 04:03:49 +0000 2024,26434,Yaelah jakarta emg KAGA BISA BET DIPUJI LU YE ...,1772836901873127452,https://pbs.twimg.com/media/GJphwkCagAArEQM.jpg,NaN,in,he/him,985,240,2767,https://twitter.com/pengwinningg/status/177283...,1125520077984419840,pengwinningg
4,1773662011546554408,Fri Mar 29 10:42:31 +0000 2024,1829,Polres Metro Jakarta Barat telah menangkap Mic...,1773662011546554408,https://pbs.twimg.com/amplify_video_thumb/1773...,NaN,in,NaN,209,252,700,https://twitter.com/kumparan/status/1773662011...,759692754985242625,kumparan

In [24]:
#Membuat DataFrame baru dengan kolom "full_text", yang diisi dengan kolom "full_text" dari DataFrame original
new_df = {
    "full_text" : df.full_text,
}

new_df = pd.DataFrame(new_df)

new_df.head()

                                           full_text
0  Waktu dpt rejection letter di satu uni di UK. ...
1  230923 SMTOWN in JAKARTA #태용 #AprilFoolsDay #만...
2  Ini harga TDS2 7Drean()scape di Jakarta setela...
3  Yaelah jakarta emg KAGA BISA BET DIPUJI LU YE ...
4  Polres Metro Jakarta Barat telah menangkap Mic...

In [25]:
def remove_urls(text):
    # Define the regex pattern to match URLs
    url_pattern = r'https?://\S+|www\.\S+'

    # Use the sub() function to replace URLs with an empty string
    return re.sub(url_pattern, '', text)

In [26]:
def remove_tags(text):
    # Define the regex pattern to match tags
    tags_pattern = r'#\S+'

    # Use the sub() function to replace tags with an empty string
    return re.sub(tags_pattern, '', text)

In [27]:
def remove_mentions(text):
    # Define the regex pattern to match mentions
    mention_pattern = r'@\S+'

    # Use the sub() function to replace mentions with an empty string
    return re.sub(mention_pattern, '', text)

In [28]:
new_df.full_text

0     Waktu dpt rejection letter di satu uni di UK. ...
1     230923 SMTOWN in JAKARTA #태용 #AprilFoolsDay #만...
2     Ini harga TDS2 7Drean()scape di Jakarta setela...
3     Yaelah jakarta emg KAGA BISA BET DIPUJI LU YE ...
4     Polres Metro Jakarta Barat telah menangkap Mic...
                            ...
95    Pakistan girl from jakarta https://t.co/bSmYyV...
96    Massge in/Outcall Vcs Jakarta dan luar kota. #...
97                 Selamat pagi https://t.co/y1kkVbO86O
98    Kaesang Belum Cukup Umur Jadi Cagub DKI Jakart...
99    Kritisi UU DKJ HNW: Berdasarkan Konstitusi UU ...
Name: full_text, Length: 100, dtype: object

In [29]:
# Mengeksekusi fungsi ke setiap baris dataframe yang ada
new_df = new_df.full_text.apply(remove_urls).apply(remove_tags).apply(remove_mentions)

In [30]:
# Menyimpan DataFrame baru menjadi CSV, dengan nama yang diberikan di parameter
new_df.to_csv("cleaned_tweets.csv")